language: php
os: linux
dist: xenial

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.3'
  - '7.4'
  - master

jobs:
  fast_finish: true
  allow_failures:
    - php: master

env:
  jobs:
    - DEPENDENCIES="lowest"   LARAVEL="5.6.*"
    - DEPENDENCIES="lowest"   LARAVEL="5.7.*"
    - DEPENDENCIES="lowest"   LARAVEL="5.8.*"
    - DEPENDENCIES="lowest"   LARAVEL="^6.0"
    - DEPENDENCIES="highest"  LARAVEL="5.6.*"
    - DEPENDENCIES="highest"  LARAVEL="5.7.*"
    - DEPENDENCIES="highest"  LARAVEL="5.8.*"
    - DEPENDENCIES="highest"  LARAVEL="^6.0"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest --no-scripts --optimize-autoloader --classmap-authoritative"

install:
  - if [[ "$DEPENDENCIES" = 'lowest' ]]; then export DEFAULT_COMPOSER_FLAGS="$DEFAULT_COMPOSER_FLAGS --prefer-lowest"; fi
  - composer require illuminate/contracts:${LARAVEL} illuminate/database:${LARAVEL} illuminate/log:${LARAVEL} illuminate/routing:${LARAVEL} illuminate/support:${LARAVEL} $DEFAULT_COMPOSER_FLAGS

before_script:
  - if php --ri xdebug >/dev/null; then phpenv config-rm xdebug.ini; fi

script:
  - composer cs-check
  - composer code-analyse
  - phpunit --bootstrap vendor/autoload.php --configuration phpunit.xml

notifications:
  email: false
